// i18n.js - 国际化配置文件
import { ref, watch } from 'vue'
import { createI18n } from 'vue-i18n'

// 创建一个响应式的语言变量，并从localStorage中获取初始值（如果有）
export const currentLang = ref(localStorage.getItem('language') || 'en-US')

// 监听语言变化并保存到localStorage并更新i18n实例的locale
watch(currentLang, (newLang) => {
  localStorage.setItem('language', newLang)
  // 这里不需要手动更新i18n实例，因为我们会在创建时绑定响应式引用
})

// 定义翻译消息
const messages = {
  'en-US': {
    appTitle: 'VSCode Extension Offline Download Tool',
    appSubtitle: 'Download VSCode extensions for offline installation',
    searchPlaceholder: 'Enter extension name or ID',
    searchButton: 'Search',
    description: 'Description',
    version: 'Version',
    lastUpdated: 'Last Updated',
    tags: 'Tags',
    categories: 'Categories',
    selectVersion: 'Select Version',
    downloadButton: 'Download Extension',
    errorNotFound: 'No matching extension found, please check the extension name or ID',
    errorNetwork: 'Search error: No server response, please check your network connection',
    errorGeneric: 'Search error: ',
    errorDownload: 'Download error: ',
    publisher: 'Publisher',
    unknown: 'Unknown',
    backButton: 'Back to Search',
    featuresTitle: 'Features',
    featuresSubtitle: 'Everything you need to download VSCode extensions',
    feature1Title: 'Easy Search',
    feature1Description: 'Search for any VSCode extension by name or ID',
    feature2Title: 'Version Selection',
    feature2Description: 'Choose specific versions of extensions for download',
    feature3Title: 'Fast Download',
    feature3Description: 'Direct download of .vsix files for offline installation',
    feature4Title: 'Extension Details',
    feature4Description: 'View comprehensive information about each extension',
    openSourceTitle: 'Open Source',
    openSourceDescription: 'This project is open source and available on GitHub',
    viewOnGithub: 'View on GitHub',
    footerText: 'Generated by Trae based on Claude-3.7-Sonnet &'
  },
  'zh-CN': {
    appTitle: 'VSCode插件离线下载工具',
    appSubtitle: '下载VSCode插件用于离线安装',
    searchPlaceholder: '请输入插件名称或ID',
    searchButton: '搜索',
    description: '描述',
    version: '版本',
    lastUpdated: '最后更新',
    tags: '标签',
    categories: '分类',
    selectVersion: '选择版本',
    downloadButton: '下载插件',
    errorNotFound: '未找到匹配的插件，请检查插件名称或ID是否正确',
    errorNetwork: '搜索插件时出错: 未收到服务器响应，请检查网络连接',
    errorGeneric: '搜索插件时出错: ',
    errorDownload: '下载插件时出错: ',
    publisher: '发布者',
    unknown: '未知',
    backButton: '返回搜索',
    featuresTitle: '功能特点',
    featuresSubtitle: '下载VSCode插件所需的一切',
    feature1Title: '便捷搜索',
    feature1Description: '通过名称或ID搜索任何VSCode插件',
    feature2Title: '版本选择',
    feature2Description: '选择特定版本的插件进行下载',
    feature3Title: '快速下载',
    feature3Description: '直接下载.vsix文件用于离线安装',
    feature4Title: '插件详情',
    feature4Description: '查看每个插件的详细信息',
    openSourceTitle: '开源项目',
    openSourceDescription: '本项目是开源的，可在GitHub上找到',
    viewOnGithub: '在GitHub上查看',
    footerText: '由 Trae 基于 Claude-3.7-Sonnet 生成 &'
  }
}

// 创建i18n实例
const i18n = createI18n({
  legacy: false, // 使用组合式API
  locale: currentLang.value, // 初始值
  fallbackLocale: 'en-US',
  messages
})

// 确保i18n实例的locale属性跟随currentLang变化
watch(currentLang, (newLang) => {
  i18n.global.locale.value = newLang
})

export default i18n